version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud:21-apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    environment:
      - NEXTCLOUD_ADMIN_USER=nextcloud
      - NEXTCLOUD_ADMIN_PASSWORD=password
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=db:3306
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost 192.168.10.110
    depends_on:
      - db
      - code

  code:
    image: collabora/code
    restart: always
    ports:
      - "9980:9980"
    environment:
      - extra_params=--o:ssl.enable=false

  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/conf.d/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

volumes:
  db:
  nextcloud:
